AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-search-product

  Sample SAM Template for lambda-search-product
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SearchProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          DATABASE_URL: 'postgresql://midasdb_qh22_user:RxGDWJVZ8A0UfDunrAjGzVdkaInlwnaa@dpg-cq7h7hmehbks738vhhq0-a.oregon-postgres.render.com/midasdb_qh22?ssl=true'
      Architectures:
        - x86_64
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  ProductsApi:
    Description: "API Gateway endpoint URL for prod stage for SearchProductsFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/products/"